Mod UltiSnipsSnippetsDir, resolve conflicts with snipMate @vimrc
Solve bug by renaming private snippets dir from "snippets" to "ultisnips".
The private snippets dir is located in ~/.vim/ultisnips now

NOTE: "snippets" is reserved for snipMate snippets

Bug: press space An error occured.

This is either a bug in UltiSnips or a bug in a snippet definition. If you
think this is a bug, please report it to
https://github.com/SirVer/ultisnips/issues/new.

Following is the full stack trace:
Traceback (most recent call last):
  File "/Users/davidpdrsn/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 53, in wrapper
    return func(self, *args, **kwds)
  File "/Users/davidpdrsn/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 116, in expand
    if not self._try_expand():
  File "/Users/davidpdrsn/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 477, in _try_expand
    snippets = self._snips(before, False)
  File "/Users/davidpdrsn/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet_manager.py", line 417, in _snips
    for snippet in source.get_snippets(filetypes, before, possible):
  File "/Users/davidpdrsn/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 36, in get_snippets
    self._ensure_loaded(ft, set())
  File "/Users/davidpdrsn/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 54, in _ensure_loaded
    if self._needs_update(ft):
  File "/Users/davidpdrsn/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/_base.py", line 63, in _needs_update
    existing_files = self._get_all_snippet_files_for(ft)
  File "/Users/davidpdrsn/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/ultisnips.py", line 136, in _get_all_snippet_files_for
    return find_all_snippet_files(ft)
  File "/Users/davidpdrsn/.vim/bundle/ultisnips/pythonx/UltiSnips/snippet/source/file/ultisnips.py", line 40, in find_all_snippet_files
    "You have 'snippets' in UltiSnipsSnippetDirectories. This "
RuntimeError: You have 'snippets' in UltiSnipsSnippetDirectories. This directory is reserved for snipMate snippets. Use another directory for UltiSnips snippets.